# Generated by Django 4.2.13 on 2024-07-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
