# Generated by Django 4.2.13 on 2024-07-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
