# Generated by Django 4.2.13 on 2024-07-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_arriendo_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
    ]
