# Generated by Django 5.1.2 on 2025-01-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_producto_destacado_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
