# Generated by Django 5.1.2 on 2025-01-23 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_boleta_boletaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(choices=[('retiro', 'Retiro en sucursal'), ('envio', 'Envío a domicilio')], max_length=10)),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=10)),
                ('nombre_comprador', models.CharField(max_length=100)),
                ('apellido_comprador', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('boleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion', to='core.boleta')),
            ],
        ),
    ]
